
{% set data = load_setup_py_data() %}

package:
  name: jmspack
  version: {{ data["version"] }}

source:
  path: .

requirements:
  build:
    - python
    - setuptools
    - seaborn >=0.11.0
    - statsmodels >=0.12.0
    - scikit-learn >=0.23.0
    - requests >=2.24.0
    - jupyter>=1.0.0
  run:
    - python
    - seaborn >=0.11.0
    - statsmodels >=0.12.0
    - scikit-learn >=0.23.0
    - requests >=2.24.0
    - jupyter>=1.0.0
